FROM openjdk:17-alpine

RUN addgroup -S spring && adduser -S spring -G spring

USER spring:spring

#WORKDIR /app

#COPY .mvn/ .mvn
#COPY mvnw pom.xml ./

#RUN ./mvnw package && java -jar target/todoapp-0.0.1-SNAPSHOT.jar

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]