name: env_var_assgn

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      -  development
   
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set docker image version
        run: 
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
        env:
          DOCKER_IMAGE_VERSION: $calculatedSha
          
      - name: Show docker version 
        run:
          echo  "fatihbe25/todo-app-backend_prv:${{env.DOCKER_IMAGE_VERSION}}"
