name: env_var_assgn

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      -  development
   
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Assign docker registry image path
        uses: actions/github-script@v3
        with:
          script:
            const sha = context.sha.substring(0,10)
            const docker_image =  `fatihbe25\todo-app-backend_prv:${sha}`
            
            core.exportVariable('DOCKER_REGISTRY_IMAGE_PATH',docker_image);
      
      - name: Show docker image path 
        run: echo "docker image => ${{ env.DOCKER_REGISTRY_IMAGE_PATH }}"
      
