name: env_var_assgn

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      -  development
   
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Variables
        uses: actions/github-script@v3
        with:
          script:
            const sha = context.sha.substring(0,10)
            
            core.exportVariable('GITHUB_SHA_SHORT',sha);
      
      - name: Show docker image path 
        run: echo "docker image => fatihbe25\todo-app-backend_prv:${{ env.GITHUB_SHA_SHORT }}"
      
